"""RAG extended sources: comments, artifacts, claims, evidence + filters."""

from __future__ import annotations

import asyncio
from datetime import UTC, datetime
from pathlib import Path

from app.infrastructure.database import Database
from app.infrastructure.database.knowledge_repository import KnowledgeRepository
from app.infrastructure.database.models import (
    ArtifactRecord,
    ClaimRecord,
    EvidenceRecord,
    SourceCommentRecord,
    SourcePostRecord,
)


async def _seed(database: Database) -> str:
    """Create one case with a post, comment, artifact, claim and evidence.

    Returns the case_id. Source ids are generated by the database, so tests
    assert on ``source_type`` membership rather than concrete evidence ids.
    """
    from app.application.repositories import ApplicationRepository
    from app.schemas.cases import CreateCaseRequest

    repository = ApplicationRepository(database)
    case = await repository.create_case(
        CreateCaseRequest(topic="新能源汽车争议", platforms=["weibo", "bilibili"])
    )
    async with database.session_factory() as session:
        post = SourcePostRecord(
            case_id=case.id,
            platform="weibo",
            native_id="p1",
            content="该批次新能源汽车已启动主动召回。",
            source_url="https://weibo.com/1",
            published_at=datetime(2026, 8, 1, tzinfo=UTC),
            content_hash="h1",
        )
        session.add(post)
        await session.flush()
        comment = SourceCommentRecord(
            post_id=post.id,
            platform="weibo",
            native_id="c1",
            content="召回公告发布后股价应声下跌。",
            published_at=datetime(2026, 8, 2, tzinfo=UTC),
        )
        session.add(comment)
        session.add(
            ArtifactRecord(
                case_id=case.id,
                kind="fact_check",
                title="召回范围核查卡",
                version=1,
                data={"verdict": "supported", "detail": "召回公告发布后股价下跌"},
            )
        )
        session.add(
            ClaimRecord(
                case_id=case.id,
                text="召回公告发布后股价下跌，本批次车辆存在电池安全隐患",
                status="open",
                created_by_run_id="00000000-0000-0000-0000-000000000001",
            )
        )
        session.add(
            EvidenceRecord(
                case_id=case.id,
                source_type="social_post",
                source_id="p1",
                stance="support",
                excerpt="官方公告显示已启动主动召回，股价随后下跌。",
            )
        )
        await session.commit()

    return case.id


def test_hybrid_search_covers_extended_sources(tmp_path: Path) -> None:
    database = Database(f"sqlite+aiosqlite:///{tmp_path / 'rag.db'}")
    asyncio.run(database.create_schema())

    async def run() -> None:
        case_id = await _seed(database)
        knowledge = KnowledgeRepository(database)
        hits = await knowledge.search(case_id=case_id, query="召回 股价", limit=20)
        types = {hit.source_type for hit in hits}
        assert "social_comment" in types, hits
        assert "artifact" in types, hits
        assert "claim" in types, hits
        assert "evidence" in types, hits

    asyncio.run(run())
    asyncio.run(database.dispose())


def test_source_types_filter(tmp_path: Path) -> None:
    database = Database(f"sqlite+aiosqlite:///{tmp_path / 'rag.db'}")
    asyncio.run(database.create_schema())

    async def run() -> None:
        case_id = await _seed(database)
        knowledge = KnowledgeRepository(database)
        hits = await knowledge.search(
            case_id=case_id,
            query="召回",
            limit=20,
            source_types={"social_comment"},
        )
        assert hits and all(hit.source_type == "social_comment" for hit in hits)

    asyncio.run(run())
    asyncio.run(database.dispose())


def test_platform_filter(tmp_path: Path) -> None:
    database = Database(f"sqlite+aiosqlite:///{tmp_path / 'rag.db'}")
    asyncio.run(database.create_schema())

    async def run() -> None:
        case_id = await _seed(database)
        knowledge = KnowledgeRepository(database)
        hits = await knowledge.search(
            case_id=case_id,
            query="召回",
            limit=20,
            source_types={"social_post", "social_comment"},
            platforms=["bilibili"],
        )
        assert hits == []  # only weibo posts/comments exist

    asyncio.run(run())
    asyncio.run(database.dispose())


def test_time_filter(tmp_path: Path) -> None:
    database = Database(f"sqlite+aiosqlite:///{tmp_path / 'rag.db'}")
    asyncio.run(database.create_schema())

    async def run() -> None:
        case_id = await _seed(database)
        knowledge = KnowledgeRepository(database)
        hits = await knowledge.search(
            case_id=case_id,
            query="召回",
            limit=20,
            source_types={"social_post"},
            time_from=datetime(2026, 8, 2, tzinfo=UTC),
        )
        # Post published 08-01 is excluded; comment 08-02 is outside source_types.
        assert hits == []

    asyncio.run(run())
    asyncio.run(database.dispose())


def test_rerank_hits_prefers_keyword_overlap() -> None:
    from app.infrastructure.database.knowledge_repository import (
        RagHit,
        rerank_hits,
    )

    overlapping = RagHit(
        evidence_id="a",
        source_type="social_post",
        source_id="1",
        content="新能源汽车召回引发热议",
        score=0.5,
    )
    unrelated = RagHit(
        evidence_id="b",
        source_type="social_post",
        source_id="2",
        content="今天天气不错适合出行",
        score=0.5,
    )
    result = rerank_hits(
        [overlapping, unrelated],
        query_terms=["新能源", "召回"],
        limit=2,
    )
    assert result[0].evidence_id == "a"
    assert result[0].score > result[1].score


def test_api_evidence_search_platform_filter(tmp_path: Path) -> None:
    from fastapi.testclient import TestClient

    from app.core.config import Settings
    from app.main import create_app

    app = create_app(
        Settings(
            database_url=f"sqlite+aiosqlite:///{tmp_path / 'api.db'}",
            demo_mode=True,
        )
    )
    with TestClient(app) as client:
        case = client.post(
            "/api/v1/cases",
            json={"topic": "新能源汽车争议", "platforms": ["weibo", "bilibili"]},
        ).json()
        case_id = case["id"]
        client.post(
            f"/api/v1/cases/{case_id}/memories",
            json={
                "kind": "fact",
                "content": "微博官方账号发布召回公告",
                "source_type": "social_post",
                "source_id": "p1",
            },
        )
        hits = client.post(
            f"/api/v1/cases/{case_id}/evidence/search",
            json={"query": "召回", "limit": 5, "platforms": ["bilibili"]},
        )
        assert hits.status_code == 200
        returned = hits.json()
        # Platform filtering applies to social sources only; the memory row
        # has no platform column and is not filtered out.
        assert len(returned) == 1
        assert returned[0]["source_type"] == "memory"
        time_hits = client.post(
            f"/api/v1/cases/{case_id}/evidence/search",
            json={
                "query": "召回",
                "limit": 5,
                "time_range": {"from": "2026-08-01T00:00:00+00:00"},
            },
        )
        assert time_hits.status_code == 200
        assert len(time_hits.json()) == 1
