"""Add durable harness runtime and evidence tables.

固定显式 schema（不反射当前 models）：当前 models 含后续迁移才引入的
Vector 类型与后加列/外键（goals、memory governance 等），反射创建会在
空库上引用尚不存在的类型/表。本迁移按 0019 时代 schema 显式建表，
后加列由各自迁移 add_column 补齐；embedding 列用 JSON（0003/0010 转 vector）。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.infrastructure.database.models import Base

revision: str = "20260729_0002"
down_revision: str | None = "20260726_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        'agent_runs',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'case_id',
            sa.String(36),
            sa.ForeignKey('cases.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'turn_id',
            sa.String(36),
            sa.ForeignKey('conversation_turns.id'),
            nullable=True,
            index=True,
        ),
        sa.Column(
            'parent_run_id',
            sa.String(36),
            sa.ForeignKey('agent_runs.id'),
            nullable=True,
            index=True,
        ),
        sa.Column(
            'agent',
            sa.String(100),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'status',
            sa.String(32),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'objective',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'model_route',
            sa.String(32),
            nullable=False,
        ),
        sa.Column(
            'input_tokens',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'output_tokens',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'tool_call_count',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'estimated_cost',
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            'error_code',
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            'error',
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            'metadata_json',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )

    op.create_table(
        'model_calls',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'run_id',
            sa.String(36),
            sa.ForeignKey('agent_runs.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'model',
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            'route',
            sa.String(32),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.String(32),
            nullable=False,
        ),
        sa.Column(
            'input_tokens',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'output_tokens',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'estimated_cost',
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            'latency_ms',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'error_code',
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )

    op.create_table(
        'run_events',
        sa.Column(
            'id',
            sa.Integer(),
            primary_key=True,
        ),
        sa.Column(
            'run_id',
            sa.String(36),
            sa.ForeignKey('agent_runs.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'event_type',
            sa.String(64),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'agent',
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            'skill',
            sa.String(160),
            nullable=True,
        ),
        sa.Column(
            'tool_call_id',
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            'tool',
            sa.String(160),
            nullable=True,
        ),
        sa.Column(
            'status',
            sa.String(32),
            nullable=False,
        ),
        sa.Column(
            'payload',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )

    op.create_table(
        'tool_calls',
        sa.Column(
            'id',
            sa.String(100),
            primary_key=True,
        ),
        sa.Column(
            'run_id',
            sa.String(36),
            sa.ForeignKey('agent_runs.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'tool_name',
            sa.String(160),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'skill_name',
            sa.String(160),
            nullable=True,
        ),
        sa.Column(
            'status',
            sa.String(32),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'arguments',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'result',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'error_code',
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            'started_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            'finished_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.create_table(
        'approvals',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'run_id',
            sa.String(36),
            sa.ForeignKey('agent_runs.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'action',
            sa.String(160),
            nullable=False,
        ),
        sa.Column(
            'reason',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.String(32),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'request_payload',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'decision_payload',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'decided_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )

    op.create_table(
        'memories',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'case_id',
            sa.String(36),
            sa.ForeignKey('cases.id'),
            nullable=True,
            index=True,
        ),
        sa.Column(
            'scope',
            sa.String(32),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'kind',
            sa.String(32),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'content',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'source_type',
            sa.String(64),
            nullable=False,
        ),
        sa.Column(
            'source_id',
            sa.String(500),
            nullable=False,
        ),
        sa.Column(
            'importance',
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            'confidence',
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            'active',
            sa.Boolean(),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'supersedes_id',
            sa.String(36),
            sa.ForeignKey('memories.id'),
            nullable=True,
        ),
        sa.Column(
            'embedding',
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            'metadata_json',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )

    op.create_table(
        'knowledge_documents',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'case_id',
            sa.String(36),
            sa.ForeignKey('cases.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'filename',
            sa.String(300),
            nullable=False,
        ),
        sa.Column(
            'media_type',
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            'checksum',
            sa.String(64),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'status',
            sa.String(32),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'metadata_json',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )

    op.create_table(
        'knowledge_chunks',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'document_id',
            sa.String(36),
            sa.ForeignKey('knowledge_documents.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'ordinal',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'content',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'token_count',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'embedding',
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            'metadata_json',
            sa.JSON(),
            nullable=False,
        ),
        sa.UniqueConstraint('document_id','ordinal'),
    )

    op.create_table(
        'source_posts',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'case_id',
            sa.String(36),
            sa.ForeignKey('cases.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'platform',
            sa.String(32),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'native_id',
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            'content_type',
            sa.String(32),
            nullable=False,
        ),
        sa.Column(
            'title',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'content',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'author_id',
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            'author_name',
            sa.String(300),
            nullable=False,
        ),
        sa.Column(
            'source_url',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'published_at',
            sa.DateTime(timezone=True),
            nullable=True,
            index=True,
        ),
        sa.Column(
            'engagement',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'raw_payload',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'content_hash',
            sa.String(64),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'embedding',
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.UniqueConstraint('platform','native_id', name='source_posts_platform_native_id_key'),
    )

    op.create_table(
        'source_comments',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'post_id',
            sa.String(36),
            sa.ForeignKey('source_posts.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'platform',
            sa.String(32),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'native_id',
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            'parent_native_id',
            sa.String(200),
            nullable=True,
        ),
        sa.Column(
            'content',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'author_id',
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            'author_name',
            sa.String(300),
            nullable=False,
        ),
        sa.Column(
            'published_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            'metrics',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'raw_payload',
            sa.JSON(),
            nullable=False,
        ),
        sa.UniqueConstraint('platform','native_id', name='source_comments_platform_native_id_key'),
    )

    op.create_table(
        'claims',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'case_id',
            sa.String(36),
            sa.ForeignKey('cases.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'text',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.String(32),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'verdict',
            sa.String(32),
            nullable=True,
        ),
        sa.Column(
            'confidence',
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            'created_by_run_id',
            sa.String(36),
            sa.ForeignKey('agent_runs.id'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )

    op.create_table(
        'evidence',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'case_id',
            sa.String(36),
            sa.ForeignKey('cases.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'claim_id',
            sa.String(36),
            sa.ForeignKey('claims.id'),
            nullable=True,
            index=True,
        ),
        sa.Column(
            'source_type',
            sa.String(32),
            nullable=False,
        ),
        sa.Column(
            'source_id',
            sa.String(500),
            nullable=False,
        ),
        sa.Column(
            'stance',
            sa.String(32),
            nullable=False,
        ),
        sa.Column(
            'excerpt',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'relevance',
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            'metadata_json',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )

    op.create_table(
        'propagation_edges',
        sa.Column(
            'id',
            sa.String(36),
            primary_key=True,
        ),
        sa.Column(
            'case_id',
            sa.String(36),
            sa.ForeignKey('cases.id'),
            nullable=False,
            index=True,
        ),
        sa.Column(
            'source_post_id',
            sa.String(36),
            sa.ForeignKey('source_posts.id'),
            nullable=False,
        ),
        sa.Column(
            'target_post_id',
            sa.String(36),
            sa.ForeignKey('source_posts.id'),
            nullable=False,
        ),
        sa.Column(
            'relation',
            sa.String(32),
            nullable=False,
        ),
        sa.Column(
            'confidence',
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            'feature_scores',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'evidence_ids',
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            'algorithm_version',
            sa.String(64),
            nullable=False,
        ),
        sa.Column(
            'human_confirmed',
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.UniqueConstraint('case_id','source_post_id','target_post_id'),
    )


def downgrade() -> None:
    bind = op.get_bind()
    for name in (
        "agent_runs",
        "model_calls",
        "run_events",
        "tool_calls",
        "approvals",
        "memories",
        "knowledge_documents",
        "knowledge_chunks",
        "source_posts",
        "source_comments",
        "claims",
        "evidence",
        "propagation_edges",
    ):
        Base.metadata.tables[name].drop(bind=bind, checkfirst=True)
    op.drop_table("agent_runs")
